# Generated by Django 5.2.5 on 2025-12-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='general_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API-ключ'),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='OpenAI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Gemini'),
        ),
    ]
