# Generated by Django 5.2.5 on 2025-12-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_general_api_key_user_openai_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='general_api_key',
        ),
        migrations.AddField(
            model_name='user',
            name='gemini_prompt',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Gemini Prompt'),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_prompt',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Openai Prompt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gemini API-KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Openai API-KEY'),
        ),
    ]
