# Generated by Django 5.2.5 on 2025-12-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_general_api_key_user_gemini_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LLM model'),
        ),
        migrations.AddField(
            model_name='user',
            name='openai_model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LLM model'),
        ),
    ]
