# Generated by Django 5.2.5 on 2025-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gemini_model_user_openai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Openai API-KEY'),
        ),
    ]
